from pathlib import Path
import json
T=Path('theme')
for d in ['layout','sections','snippets','templates','config','locales','assets']: (T/d).mkdir(parents=True,exist_ok=True)
def put(p,s): (T/p).write_text(s.strip()+'\n')
def js(p,o): put(p,json.dumps(o,indent=2))
def setting(t,id,label,default=None,**kw):
 d=dict(type=t,id=id,label=label,**kw)
 if default is not None:d['default']=default
 return d
def section(name,markup,settings=[],blocks=[],presets=True):
 schema={'name':name,'settings':settings}
 if blocks:schema['blocks']=blocks
 if presets:schema['presets']=[{'name':name}]
 return markup+'\n{% schema %}\n'+json.dumps(schema,indent=2)+'\n{% endschema %}'
def tpl(name,sections):
 js('templates/'+name+'.json',{'sections':{k:{'type':typ,**extra} for k,typ,extra in sections},'order':[x[0] for x in sections]})
js('config/settings_schema.json',[
 {'name':'theme_info','theme_name':'Kneora','theme_version':'1.0.0','theme_author':'Kneora'},
 {'name':'Brand','settings':[setting('text','brand','Brand name','Kneora'),setting('color','navy','Workwear navy','#20364B'),setting('color','paper','Chalk white','#FAFCFD'),setting('color','accent','Amber','#D5A442'),setting('font_picker','heading_font','Heading font','assistant_n7'),setting('font_picker','body_font','Body font','assistant_n4'),setting('image_picker','favicon','Favicon')]},
 {'name':'Store links','settings':[setting('product','main_product','Main Kneora product'),setting('link_list','main_menu','Main menu','main-menu'),setting('link_list','footer_menu','Footer menu','footer'),setting('url','guide_url','Product guide'),setting('url','story_url','Our story'),setting('url','support_url','Support page'),setting('text','support_email','Support email'),setting('text','support_hours','Support hours')]}
])
js('config/settings_data.json',{'current':{}})
loc={'general':{'skip':'Skip to content','menu':'Menu','close':'Close','shop':'Shop','guide':'How it works','story':'Our story','support':'Support','cart':'Cart','search':'Search','checkout':'Checkout','continue':'Continue shopping','empty':'Your cart is empty.','remove':'Remove','update':'Update cart','quantity':'Quantity','name':'Name','email':'Email','message':'Message','send':'Send message','sent':'Thanks. Your message has been sent.','search_label':'Search the store','search_empty':'No results found. Try another search.','previous':'Previous','next':'Next','password':'Store password','enter':'Enter store','password_intro':'Something considered is on its way.','not_found':'This page has moved on.','not_found_text':'Find your way back to the store.','home':'Back to home','shipping_note':'Shipping and taxes calculated at checkout.'},'product':{'choose':'Choose your package','once':'One-time purchase','add':'Add to cart','sold':'Sold out','unavailable':'Unavailable','adding':'Adding…','added':'Added to your cart.','error':'Could not add this item. Please try again.','view_cart':'View cart','details':'Product details','zoom':'Enlarge product image','media':'Product media','reviews':'Customer stories','single':'Single Kneora Massager','bundle':'Kneora Knee Massager + After Care Healing Gel','single_contents':'One dual-knee massager','bundle_contents':'One dual-knee massager + one gel','bundle_label':'After-work care set','save':'Save','choose_again':'Choose your package','shipping':'Shipping information','returns':'Returns policy','missing':'Choose the main product in Theme settings → Store links.','image_missing':'Add approved product photography to the Shopify product gallery.','preview':'Theme editor preview only'},'contact':{'title':'A little help goes a long way.','intro':'Questions about your Kneora? Get in touch.'},'newsletter':{'label':'Email updates','button':'Sign up','success':'You’re on the list.'},'cart':{'title':'Your cart','subtotal':'Subtotal','updated':'Cart updated.','error':'Could not update your cart. Please try again.'}}
js('locales/en.default.json',loc)
put('layout/theme.liquid','''<!doctype html>
<html lang="{{ request.locale.iso_code }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ page_title | escape }}{% unless page_title contains shop.name %} — {{ shop.name | escape }}{% endunless %}</title>
{% if page_description %}<meta name="description" content="{{ page_description | escape }}">{% endif %}
<link rel="canonical" href="{{ canonical_url }}">
{% if settings.favicon %}<link rel="icon" href="{{ settings.favicon | image_url: width: 32 }}">{% endif %}
{{ content_for_header }}
{% style %}
{{ settings.heading_font | font_face: font_display: 'swap' }}
{{ settings.body_font | font_face: font_display: 'swap' }}
:root{--navy:{{ settings.navy }};--paper:{{ settings.paper }};--amber:{{ settings.accent }};--heading:{{ settings.heading_font.family }},{{ settings.heading_font.fallback_families }};--body:{{ settings.body_font.family }},{{ settings.body_font.fallback_families }};}
{% endstyle %}
{{ 'kneora.css' | asset_url | stylesheet_tag }}
<script src="{{ 'kneora.js' | asset_url }}" defer></script>
</head>
<body data-cart-url="{{ routes.cart_url }}" data-root="{{ routes.root_url }}">
<a class="skip-link" href="#MainContent">{{ 'general.skip' | t }}</a>
{% sections 'header-group' %}
<main id="MainContent">{{ content_for_layout }}</main>
{% sections 'footer-group' %}
<dialog id="CartDrawer" class="drawer" aria-labelledby="CartTitle"><div class="drawer-top"><h2 id="CartTitle">{{ 'cart.title' | t }}</h2><button type="button" data-close aria-label="{{ 'general.close' | t }}">×</button></div><div data-cart-content></div></dialog>
<div hidden id="CartTranslations" data-error="{{ 'cart.error' | t }}"></div>
</body></html>''')
put('sections/header.liquid',section('Header','''{% if section.settings.announcement != blank %}<div class="announcement">{{ section.settings.announcement | escape }}</div>{% endif %}
<header class="site-header wrap">
<a class="wordmark" href="{{ routes.root_url }}">{{ settings.brand | escape }}<span aria-hidden="true">®</span></a>
<nav class="desktop-nav" aria-label="{{ 'general.menu' | t }}">
{% if settings.main_menu.links.size > 0 %}{% for link in settings.main_menu.links %}<a href="{{ link.url }}" {% if link.current %}aria-current="page"{% endif %}>{{ link.title | escape }}</a>{% endfor %}{% else %}<a href="{{ routes.all_products_collection_url }}">{{ 'general.shop' | t }}</a>{% endif %}
</nav>
<div class="header-actions"><a class="search-link" href="{{ routes.search_url }}">{{ 'general.search' | t }}</a><a href="{{ routes.cart_url }}" data-open-cart>{{ 'general.cart' | t }} <span data-cart-count>{{ cart.item_count }}</span></a><button class="mobile-menu" data-open="MobileMenu" aria-haspopup="dialog">{{ 'general.menu' | t }}</button></div>
</header>
<dialog id="MobileMenu" class="drawer menu-drawer" aria-label="{{ 'general.menu' | t }}"><div class="drawer-top"><span class="wordmark">{{ settings.brand | escape }}</span><button data-close aria-label="{{ 'general.close' | t }}">×</button></div><nav>{% for link in settings.main_menu.links %}<a href="{{ link.url }}">{{ link.title | escape }}</a>{% endfor %}<a href="{{ routes.search_url }}">{{ 'general.search' | t }}</a></nav></dialog>''',[setting('text','announcement','Announcement','One device. Both knees. Your after-work routine.')],presets=False))
js('sections/header-group.json',{'type':'header','name':'Header','sections':{'header':{'type':'header','settings':{}}},'order':['header']})
put('sections/footer.liquid',section('Footer','''<footer class="site-footer"><div class="wrap footer-grid"><div><a class="wordmark" href="{{ routes.root_url }}">{{ settings.brand | escape }}</a><p class="footer-statement">{{ section.settings.statement | escape }}</p></div><nav aria-label="{{ 'general.support' | t }}">{% for link in settings.footer_menu.links %}<a href="{{ link.url }}">{{ link.title | escape }}</a>{% endfor %}{% for policy in shop.policies %}{% if policy.body != blank %}<a href="{{ policy.url }}">{{ policy.title | escape }}</a>{% endif %}{% endfor %}</nav><div>{% if settings.support_email != blank %}<a href="mailto:{{ settings.support_email | escape }}">{{ settings.support_email | escape }}</a>{% endif %}{% if settings.support_hours != blank %}<p>{{ settings.support_hours | escape }}</p>{% endif %}{% if section.settings.newsletter %}{% form 'customer' %}<input type="hidden" name="contact[tags]" value="newsletter"><label for="FooterEmail">{{ 'newsletter.label' | t }}</label><div class="inline-form"><input id="FooterEmail" type="email" name="contact[email]" autocomplete="email" required><button>{{ 'newsletter.button' | t }}</button></div>{{ form.errors | default_errors }}{% if form.posted_successfully? %}<p role="status">{{ 'newsletter.success' | t }}</p>{% endif %}{% endform %}{% endif %}</div></div><div class="wrap footer-bottom"><span>© {{ 'now' | date: '%Y' }} {{ settings.brand | escape }}</span><div class="payment-icons">{% for type in shop.enabled_payment_types %}{{ type | payment_type_svg_tag }}{% endfor %}</div></div></footer>''',[setting('text','statement','Brand statement','For the hours you call your own.'),setting('checkbox','newsletter','Enable email signup',False)],presets=False))
js('sections/footer-group.json',{'type':'footer','name':'Footer','sections':{'footer':{'type':'footer','settings':{}}},'order':['footer']})
put('snippets/product-card.liquid','''{% doc %}
Renders a catalog product.
@param {product} item - Catalog product
{% enddoc %}
<article class="product-card"><a href="{{ item.url }}">{% if item.featured_image %}<div class="card-media">{{ item.featured_image | image_url: width: 900 | image_tag: loading: 'lazy', widths: '360,600,900' }}</div>{% endif %}<div class="card-info"><h3>{{ item.title | escape }}</h3><span>{{ item.price | money }}</span></div>{% unless item.available %}<span>{{ 'product.sold' | t }}</span>{% endunless %}</a></article>''')
put('snippets/gallery.liquid','''{% doc %}
Renders product gallery and zoom dialog.
@param {product} item - Product
@param {string} uid - Unique section identifier
{% enddoc %}
<kneora-gallery class="gallery">
<div class="gallery-stage" aria-label="{{ 'product.media' | t }}">
{% for media in item.media %}<div class="gallery-slide" data-slide="{{ media.id }}" {% unless forloop.first %}hidden{% endunless %}>
{% case media.media_type %}{% when 'image' %}<button type="button" class="zoom-trigger" data-zoom aria-label="{{ 'product.zoom' | t }}">{% if forloop.first %}{{ media | image_url: width: 1600 | image_tag: loading: 'eager', fetchpriority: 'high', widths: '400,700,1000,1600' }}{% else %}{{ media | image_url: width: 1600 | image_tag: loading: 'lazy', widths: '400,700,1000,1600' }}{% endif %}<span class="zoom-plus" aria-hidden="true">+</span></button>{% when 'video' %}{{ media | video_tag: controls: true, autoplay: false, preload: 'metadata' }}{% when 'external_video' %}{{ media | external_video_tag }}{% else %}{{ media | media_tag }}{% endcase %}</div>{% endfor %}
{% if item.media.size == 0 and request.design_mode %}<div class="editor-placeholder">{{ 'product.image_missing' | t }}</div>{% endif %}
</div>
{% if item.media.size > 1 %}<div class="gallery-thumbs">{% for media in item.media %}<button type="button" data-show="{{ media.id }}" aria-label="{{ media.alt | default: item.title | escape }} {{ forloop.index }}" aria-pressed="{% if forloop.first %}true{% else %}false{% endif %}">{{ media.preview_image | image_url: width: 160 | image_tag: loading: 'lazy' }}</button>{% endfor %}</div>{% endif %}
<dialog id="Zoom-{{ uid }}" class="zoom-dialog" aria-label="{{ 'product.zoom' | t }}"><button type="button" data-close aria-label="{{ 'general.close' | t }}">×</button><img data-zoom-image alt="" width="1200" height="1200"></dialog>
</kneora-gallery>''')
product_markup='''{% liquid
assign item = product
if item == blank
  assign item = settings.main_product
endif
assign current = item.selected_or_first_available_variant
assign form_id = 'ProductForm-' | append: section.id
%}
{% if item != blank %}
<kneora-product class="wrap product-layout {% if item.media.size == 0 %}no-product-media{% endif %}" id="Purchase-{{ section.id }}" data-add="{{ 'product.add' | t }}" data-sold="{{ 'product.sold' | t }}" data-adding="{{ 'product.adding' | t }}" data-error="{{ 'product.error' | t }}" data-added="{{ 'product.added' | t }}">
{% render 'gallery', item: item, uid: section.id %}
<div class="purchase-panel"><p class="product-name">{{ item.title | escape }}</p><h1>{{ section.settings.headline | escape }}</h1><p class="lede">{{ section.settings.subhead | escape }}</p>
<ul class="benefits">{% for block in section.blocks %}{% if block.type == 'benefit' %}<li {{ block.shopify_attributes }}><span aria-hidden="true">✓</span>{{ block.settings.text | escape }}</li>{% endif %}{% endfor %}</ul>
{% form 'product', item, id: form_id, class: 'product-form' %}
<fieldset class="offers"><legend>{{ 'product.choose' | t }}</legend>
{% for variant in item.variants %}<label class="offer {% if variant.id == current.id %}selected{% endif %}"><input type="radio" name="id" value="{{ variant.id }}" {% if variant.id == current.id %}checked{% endif %} data-title="{{ variant.title | escape }}" data-price="{{ variant.price | money | escape }}" data-available="{{ variant.available }}" data-media="{{ variant.featured_media.id }}"><span class="offer-body"><span class="offer-title">{% if item.has_only_default_variant %}{{ item.title | escape }}{% else %}{{ variant.title | escape }}{% endif %}</span><span class="offer-price">{{ variant.price | money }}{% if variant.compare_at_price > variant.price %} <s>{{ variant.compare_at_price | money }}</s>{% endif %}</span>{% if forloop.index == 1 and section.settings.single_contents != blank %}<small>{{ section.settings.single_contents | escape }}</small>{% elsif forloop.index == 2 and section.settings.bundle_contents != blank %}<small>{{ section.settings.bundle_contents | escape }}</small>{% endif %}{% unless variant.available %}<small>{{ 'product.sold' | t }}</small>{% endunless %}</span></label>{% endfor %}
</fieldset>
<div class="purchase-meta"><span>{{ 'product.once' | t }}</span><strong data-selected-price>{{ current.price | money }}</strong></div>
<div class="buy-row"><label class="quantity-label" for="Qty-{{ section.id }}">{{ 'general.quantity' | t }}<input id="Qty-{{ section.id }}" type="number" name="quantity" value="1" min="1" step="1" inputmode="numeric"></label><button type="submit" name="add" class="button" data-add-button {% unless current.available %}disabled{% endunless %}>{% if current.available %}{{ 'product.add' | t }}{% else %}{{ 'product.sold' | t }}{% endif %}</button></div>
<p class="form-status" data-product-status role="status" aria-live="polite"></p>
{% endform %}
<div class="reassurance">{% if section.settings.reassurance != blank %}<p>{{ section.settings.reassurance | escape }}</p>{% endif %}{% if shop.shipping_policy.body != blank %}<a href="{{ shop.shipping_policy.url }}">{{ 'product.shipping' | t }}</a>{% endif %}{% if shop.refund_policy.body != blank %}<a href="{{ shop.refund_policy.url }}">{{ 'product.returns' | t }}</a>{% endif %}</div>
<div class="purchase-faq">{% for block in section.blocks %}{% if block.type == 'faq' %}<details {{ block.shopify_attributes }}><summary>{{ block.settings.question | escape }}</summary><div class="rte">{{ block.settings.answer }}</div></details>{% endif %}{% endfor %}</div>
{% if item.description != blank %}<details><summary>{{ 'product.details' | t }}</summary><div class="rte">{{ item.description }}</div></details>{% endif %}
{% for block in section.blocks %}{% if block.type == '@app' %}{% render block %}{% endif %}{% endfor %}
</div>
<div class="sticky-buy" hidden><div><span data-selected-title>{{ current.title | escape }}</span><strong data-sticky-price>{{ current.price | money }}</strong></div><button type="submit" form="{{ form_id }}" class="button" data-add-button {% unless current.available %}disabled{% endunless %}>{{ 'product.add' | t }}</button></div>
</kneora-product><script type="application/ld+json">{{ item | structured_data }}</script>
{% elsif request.design_mode %}<div class="wrap section-space editor-placeholder">{{ 'product.missing' | t }}</div>{% endif %}'''
put('sections/main-product.liquid',section('Kneora product',product_markup,[setting('text','headline','Headline','The workday ends. Make room for knee care.'),setting('textarea','subhead','Introduction','A dual-knee massager with heat, massage, and red and blue light for your at-home routine.'),setting('text','single_contents','First option contents'),setting('text','bundle_contents','Second option contents'),setting('text','reassurance','Confirmed shipping / guarantee details')],[{'type':'benefit','name':'Benefit','settings':[setting('text','text','Text','One device for both knees')]},{'type':'faq','name':'Purchase question','settings':[setting('text','question','Question','Does it fit both knees?'),setting('richtext','answer','Answer','<p>One unit has two separate knee openings for both knees together.</p>')]},{'type':'@app'}]))
put('sections/home-hero.liquid',section('Brand introduction','''{% assign destination = settings.main_product.url | default: routes.all_products_collection_url %}<section class="home-hero"><div class="wrap hero-grid"><div class="hero-copy"><h1>{{ section.settings.heading | escape }}</h1><p>{{ section.settings.text | escape }}</p><a class="button" href="{{ destination }}">{{ 'general.shop' | t }} {{ settings.brand | escape }}</a><p class="hero-note">{{ section.settings.note | escape }}</p></div><div class="hero-art">{% if section.settings.image %}{{ section.settings.image | image_url: width: 1600 | image_tag: loading: 'eager', fetchpriority: 'high', widths: '600,1000,1600' }}{% elsif settings.main_product.featured_image %}{{ settings.main_product.featured_image | image_url: width: 1600 | image_tag: loading: 'eager', widths: '600,1000,1600' }}{% else %}<div class="brand-composition"><span>{{ settings.brand | escape }}</span><p>{{ section.settings.art_text | escape }}</p><div class="brand-rule"></div><small>360 × 242 × 160 mm</small></div>{% endif %}</div></div></section>''',[setting('text','heading','Headline','For the hours you call your own.'),setting('textarea','text','Introduction','Long days ask a lot of your knees. Make space for a straightforward at-home routine with Kneora.'),setting('text','note','Supporting detail','One device. Two knee openings.'),setting('image_picker','image','Approved hero photograph'),setting('text','art_text','Brand panel text','A considered approach to knee care.')]))
put('sections/editorial.liquid',section('Editorial story','''{% if section.settings.enabled %}<section class="editorial section-space {% if section.settings.dark %}dark-section{% endif %}"><div class="wrap editorial-grid {% if section.settings.reverse %}reverse{% endif %}"><div><h2>{{ section.settings.heading | escape }}</h2><div class="rte lede">{{ section.settings.text }}</div>{% if section.settings.link != blank %}<a class="text-link" href="{{ section.settings.link }}">{{ section.settings.link_label | escape }}</a>{% endif %}</div>{% if section.settings.image %}<div class="editorial-media">{{ section.settings.image | image_url: width: 1400 | image_tag: loading: 'lazy', widths: '400,700,1000,1400' }}</div>{% elsif section.blocks.size > 0 %}<div class="spec-list">{% for block in section.blocks %}<div {{ block.shopify_attributes }}><h3>{{ block.settings.title | escape }}</h3><div class="rte">{{ block.settings.text }}</div></div>{% endfor %}</div>{% endif %}</div></section>{% endif %}''',[setting('checkbox','enabled','Show section',True),setting('text','heading','Heading','Designed around both knees.'),setting('richtext','text','Text','<p>One continuous housing. Two separate knee openings. A central divider keeps the shape clear and considered.</p>'),setting('checkbox','dark','Navy background',False),setting('checkbox','reverse','Reverse desktop columns',False),setting('image_picker','image','Approved image'),setting('url','link','Link'),setting('text','link_label','Link label','Explore the details')],[{'type':'detail','name':'Detail','settings':[setting('text','title','Title','360 × 242 × 160 mm'),setting('richtext','text','Text','<p>Overall device dimensions.</p>')]}]))
put('sections/steps.liquid',section('Product guide','''{% if section.blocks.size > 0 %}<section class="wrap section-space"><div class="section-heading"><h2>{{ section.settings.heading | escape }}</h2><p>{{ section.settings.intro | escape }}</p></div><ol class="steps">{% for block in section.blocks %}<li {{ block.shopify_attributes }}>{% if block.settings.image %}{{ block.settings.image | image_url: width: 800 | image_tag: loading: 'lazy' }}{% endif %}<span class="step-number">{{ forloop.index }}</span><h3>{{ block.settings.title | escape }}</h3><div class="rte">{{ block.settings.text }}</div></li>{% endfor %}</ol></section>{% elsif request.design_mode %}<div class="wrap editor-placeholder">Add manufacturer-confirmed usage steps in this section.</div>{% endif %}''',[setting('text','heading','Heading','A routine that fits your evening.'),setting('textarea','intro','Introduction','Follow the instructions supplied with your device.')],[{'type':'step','name':'Step','settings':[setting('image_picker','image','Instruction image'),setting('text','title','Heading','Get comfortable'),setting('richtext','text','Manufacturer-confirmed instructions')]}]))
put('sections/testimonials.liquid',section('Customer stories','''{% assign has_stories = false %}{% for block in section.blocks %}{% if block.type == '@app' or block.settings.quote != blank %}{% assign has_stories = true %}{% endif %}{% endfor %}{% if has_stories %}<section class="wrap section-space" id="Reviews"><div class="section-heading"><h2>{{ section.settings.heading | escape }}</h2></div><div class="stories">{% for block in section.blocks %}{% if block.type == '@app' %}<div class="review-app">{% render block %}</div>{% elsif block.settings.quote != blank %}<figure {{ block.shopify_attributes }}>{% if block.settings.image %}{{ block.settings.image | image_url: width: 650 | image_tag: loading: 'lazy' }}{% endif %}<blockquote>{{ block.settings.quote | escape }}</blockquote><figcaption><strong>{{ block.settings.name | escape }}</strong><span>{{ block.settings.context | escape }}</span></figcaption></figure>{% endif %}{% endfor %}</div></section>{% elsif request.design_mode %}<section class="wrap section-space editor-placeholder"><h2>{{ section.settings.heading | escape }}</h2><p>Add genuine customer stories or a review app. This empty section is hidden outside the theme editor.</p></section>{% endif %}''',[setting('text','heading','Heading','In good company.')],[{'type':'story','name':'Genuine customer story','settings':[setting('image_picker','image','Customer-approved photo'),setting('textarea','quote','Real customer quote'),setting('text','name','Customer name'),setting('text','context','Customer-provided context')]},{'type':'@app'}]))
put('sections/faq.liquid',section('Questions and answers','''{% if section.blocks.size > 0 %}<section class="wrap section-space faq-layout"><h2>{{ section.settings.heading | escape }}</h2><div>{% for block in section.blocks %}<details {{ block.shopify_attributes }}><summary>{{ block.settings.question | escape }}</summary><div class="rte">{{ block.settings.answer }}</div></details>{% endfor %}</div></section>{% endif %}''',[setting('text','heading','Heading','Good questions. Clear answers.')],[{'type':'question','name':'Question','settings':[setting('text','question','Question','Does one device serve both knees?'),setting('richtext','answer','Answer','<p>Yes. One unit has two separate knee openings and a central divider.</p>')]}]))
put('sections/comparison.liquid',section('Package comparison','''{% if section.settings.enabled %}<section class="wrap section-space"><div class="section-heading"><h2>{{ section.settings.heading | escape }}</h2></div><div class="table-scroll"><table><caption class="visually-hidden">{{ section.settings.heading | escape }}</caption><thead><tr><th scope="col">{{ section.settings.column_feature | escape }}</th><th scope="col">{{ 'product.single' | t }}</th><th scope="col">{{ 'product.bundle_label' | t }}</th></tr></thead><tbody>{% for block in section.blocks %}<tr {{ block.shopify_attributes }}><th scope="row">{{ block.settings.feature | escape }}</th><td>{{ block.settings.single | escape }}</td><td>{{ block.settings.bundle | escape }}</td></tr>{% endfor %}</tbody></table></div></section>{% endif %}''',[setting('checkbox','enabled','Show comparison',False),setting('text','heading','Heading','Choose what belongs in your routine.'),setting('text','column_feature','First column heading','Included')],[{'type':'row','name':'Comparison row','settings':[setting('text','feature','Feature','Dual-knee massager'),setting('text','single','Single package','One'),setting('text','bundle','Bundle package','One')]}]))
put('sections/closing-cta.liquid',section('Closing invitation','''{% assign destination = settings.main_product.url | default: routes.all_products_collection_url %}<section class="closing"><div class="wrap"><h2>{{ section.settings.heading | escape }}</h2><p>{{ section.settings.text | escape }}</p>{% if template.name == 'product' %}<a class="button light" href="#Purchase-{{ section.settings.purchase_section }}" data-return-purchase>{{ 'product.choose_again' | t }}</a>{% else %}<a class="button light" href="{{ destination }}">{{ 'general.shop' | t }} {{ settings.brand | escape }}</a>{% endif %}</div></section>''',[setting('text','heading','Heading','Your next shift can wait a moment.'),setting('textarea','text','Text','Make some room for yourself when the workday is done.'),setting('text','purchase_section','Purchase anchor fallback','main')]))
put('sections/featured-products.liquid',section('Featured collection','''<section class="wrap section-space"><div class="section-heading"><h2>{{ section.settings.heading | escape }}</h2><a class="text-link" href="{{ routes.all_products_collection_url }}">{{ 'general.shop' | t }}</a></div><div class="product-grid">{% if section.settings.collection %}{% for item in section.settings.collection.products limit: 4 %}{% render 'product-card', item: item %}{% endfor %}{% elsif settings.main_product %}{% render 'product-card', item: settings.main_product %}{% endif %}</div></section>''',[setting('text','heading','Heading','Meet your after-work routine.'),setting('collection','collection','Featured collection')]))
put('sections/main-collection.liquid',section('Collection','''<section class="wrap section-space"><div class="section-heading"><h1>{{ collection.title | escape }}</h1><div class="rte">{{ collection.description }}</div></div>{% paginate collection.products by 12 %}<div class="product-grid">{% for item in collection.products %}{% render 'product-card', item: item %}{% endfor %}</div>{{ paginate | default_pagination }}</section>{% endpaginate %}''',presets=False))
put('sections/main-page.liquid',section('Page','''<section class="wrap section-space narrow"><h1>{{ page.title | escape }}</h1><div class="rte">{{ page.content }}</div></section>''',presets=False))
put('sections/contact.liquid',section('Contact','''<section class="wrap section-space contact-grid"><div><h1>{{ 'contact.title' | t }}</h1><p class="lede">{{ 'contact.intro' | t }}</p>{% if settings.support_email != blank %}<a class="text-link" href="mailto:{{ settings.support_email | escape }}">{{ settings.support_email | escape }}</a>{% endif %}{% if settings.support_hours != blank %}<p>{{ settings.support_hours | escape }}</p>{% endif %}</div>{% form 'contact', class: 'contact-form' %}{{ form.errors | default_errors }}{% if form.posted_successfully? %}<p role="status">{{ 'general.sent' | t }}</p>{% endif %}<label for="ContactName">{{ 'general.name' | t }}</label><input id="ContactName" name="contact[name]" autocomplete="name" value="{{ form.name | escape }}"><label for="ContactEmail">{{ 'general.email' | t }}</label><input id="ContactEmail" name="contact[email]" type="email" required autocomplete="email" value="{{ form.email | escape }}"><label for="ContactBody">{{ 'general.message' | t }}</label><textarea id="ContactBody" name="contact[body]" rows="6" required>{{ form.body | escape }}</textarea><button class="button">{{ 'general.send' | t }}</button>{% endform %}</section>'''))
put('sections/main-search.liquid',section('Search','''<section class="wrap section-space"><h1>{{ 'general.search' | t }}</h1><form action="{{ routes.search_url }}" method="get" role="search" class="search-form"><label for="SearchInput">{{ 'general.search_label' | t }}</label><div class="inline-form"><input id="SearchInput" type="search" name="q" value="{{ search.terms | escape }}" required><button class="button">{{ 'general.search' | t }}</button></div></form>{% if search.performed %}{% paginate search.results by 12 %}<div class="product-grid">{% for item in search.results %}{% if item.object_type == 'product' %}{% render 'product-card', item: item %}{% else %}<article><h2><a href="{{ item.url }}">{{ item.title | escape }}</a></h2></article>{% endif %}{% else %}<p>{{ 'general.search_empty' | t }}</p>{% endfor %}</div>{{ paginate | default_pagination }}{% endpaginate %}{% endif %}</section>''',presets=False))
put('snippets/cart-content.liquid','''{% doc %}
Renders the server-side cart form for both cart page and drawer.
{% enddoc %}
{% if cart.empty? %}<div class="empty-cart"><p>{{ 'general.empty' | t }}</p><a class="button" href="{{ routes.all_products_collection_url }}">{{ 'general.continue' | t }}</a></div>{% else %}<form action="{{ routes.cart_url }}" method="post" class="cart-form"><div class="cart-items">{% for item in cart.items %}<div class="cart-item">{% if item.image %}{{ item.image | image_url: width: 240 | image_tag: loading: 'lazy' }}{% endif %}<div><a href="{{ item.url }}"><strong>{{ item.product.title | escape }}</strong></a>{% unless item.product.has_only_default_variant %}<p>{{ item.variant.title | escape }}</p>{% endunless %}<div>{{ item.final_line_price | money }}</div><label for="CartQty-{{ forloop.index }}">{{ 'general.quantity' | t }}</label><input id="CartQty-{{ forloop.index }}" name="updates[]" type="number" min="0" step="1" value="{{ item.quantity }}" data-line="{{ forloop.index }}"><a href="{{ item.url_to_remove }}">{{ 'general.remove' | t }}</a></div></div>{% endfor %}</div><div class="cart-total"><span>{{ 'cart.subtotal' | t }}</span><strong>{{ cart.total_price | money }}</strong></div>{% for discount in cart.cart_level_discount_applications %}<p>{{ discount.title | escape }} −{{ discount.total_allocated_amount | money }}</p>{% endfor %}<p>{{ 'general.shipping_note' | t }}</p><button class="button secondary" name="update">{{ 'general.update' | t }}</button><button class="button" name="checkout">{{ 'general.checkout' | t }}</button></form>{% endif %}''')
put('sections/main-cart.liquid',section('Cart','''<section class="wrap section-space narrow"><h1>{{ 'cart.title' | t }}</h1>{% render 'cart-content' %}</section>''',presets=False))
put('sections/cart-drawer-content.liquid',section('Cart drawer content',"{% render 'cart-content' %}",presets=False))
put('sections/main-404.liquid',section('Not found','''<section class="wrap section-space narrow"><p>404</p><h1>{{ 'general.not_found' | t }}</h1><p>{{ 'general.not_found_text' | t }}</p><a class="button" href="{{ routes.root_url }}">{{ 'general.home' | t }}</a></section>''',presets=False))
put('sections/password.liquid',section('Password','''<section class="password-page wrap"><span class="wordmark">{{ settings.brand | escape }}</span><h1>{{ 'general.password_intro' | t }}</h1><div class="rte">{{ shop.password_message }}</div>{% form 'storefront_password' %}{{ form.errors | default_errors }}<label for="StorePassword">{{ 'general.password' | t }}</label><input id="StorePassword" type="password" name="password" required autocomplete="current-password"><button class="button">{{ 'general.enter' | t }}</button>{% endform %}</section>''',presets=False))
# Template presets use only confirmed facts.
benefits={f'b{i}':{'type':'benefit','settings':{'text':s}} for i,s in enumerate(['An at-home routine after the workday','One device for both knees together','Heat and massage functions','Red and blue light functions'])}
faq={'f1':{'type':'faq','settings':{'question':'Is this one device for both knees?','answer':'<p>Yes. The housing has two separate knee openings with a central divider.</p>'}},'f2':{'type':'faq','settings':{'question':'How large is the device?','answer':'<p>The overall dimensions are 360 × 242 × 160 mm. Overall dimensions do not specify the internal fitting range.</p>'}}}
mainextra={'blocks':benefits|faq,'block_order':list(benefits)+list(faq)}
details={'blocks':{'d1':{'type':'detail','settings':{'title':'Two separate openings','text':'<p>One continuous housing, with a channel for each knee.</p>'}},'d2':{'type':'detail','settings':{'title':'360 × 242 × 160 mm','text':'<p>Overall device dimensions.</p>'}},'d3':{'type':'detail','settings':{'title':'A clear central control panel','text':'<p>A blue-lit display on the top of the housing.</p>'}}},'block_order':['d1','d2','d3']}
faqextra={'blocks':{'q1':{'type':'question','settings':{'question':'Is Kneora a fabric knee wrap?','answer':'<p>No. Kneora is a rigid dual-knee unit with a white shell and separate knee openings.</p>'}},'q2':{'type':'question','settings':{'question':'Where can I find use and care instructions?','answer':'<p>Follow the instructions provided with your device. Contact the store if you need help finding your product documentation.</p>'}}},'block_order':['q1','q2']}
productsections=[('main','main-product',mainextra),('stories','testimonials',{}),('authority','editorial',{'settings':{'enabled':False,'heading':'A closer look at the evidence.','text':'<p>Add a verified expert explanation and its source before enabling this section.</p>'}}),('construction','editorial',details),('guide','steps',{}),('audience','editorial',{'settings':{'dark':True,'heading':'Built into your evening.','text':'<p>On the tools. On your feet. Down at floor level. Skilled work asks a lot of you. Your time at home deserves consideration, too.</p>'}}),('comparison','comparison',{}),('technology','editorial',{'settings':{'enabled':False,'heading':'Get to know the controls.'}}),('faq','faq',faqextra),('closing','closing-cta',{})]
tpl('product',productsections)
tpl('index',[('hero','home-hero',{}),('featured','featured-products',{}),('construction','editorial',details),('audience','editorial',{'settings':{'dark':True,'heading':'Care belongs in your toolkit.','text':'<p>For people who build, fit, fix and finish. Kneora makes space for a considered at-home routine after a demanding day.</p>'}}),('stories','testimonials',{}),('closing','closing-cta',{})])
for name,typ in [('collection','main-collection'),('page','main-page'),('page.contact','contact'),('cart','main-cart'),('search','main-search'),('404','main-404'),('password','password')]:tpl(name,[('main',typ,{})])
tpl('page.about',[('intro','editorial',{'settings':{'heading':'Good work deserves time off.','text':'<p>Kneora is a considered approach to at-home knee care for people who work with their hands. Practical equipment. Straightforward information. Space for the hours that belong to you.</p>'}}),('closing','closing-cta',{})])
tpl('page.guide',[('intro','editorial',details),('steps','steps',{}),('faq','faq',faqextra)])
