const {Liquid}=require('liquidjs');const fs=require('fs');const path=require('path');
const out=path.resolve('preview');fs.mkdirSync(out,{recursive:true});fs.mkdirSync(path.join(out,'snippets'),{recursive:true});
const clean=s=>s.replace(/{% schema %}[\s\S]*?{% endschema %}/g,'').replace(/{% doc %}[\s\S]*?{% enddoc %}/g,'').replace(/{% form [\s\S]*?%}/g,tag=>tag.includes("'product'")?'<form class="product-form">':'<form>').replace(/{% endform %}/g,'</form>').replace(/{% paginate .*?%}/g,'').replace(/{% endpaginate %}/g,'');
for(const f of fs.readdirSync('theme/snippets'))fs.writeFileSync(path.join(out,'snippets',f),clean(fs.readFileSync('theme/snippets/'+f,'utf8')));
const engine=new Liquid({root:path.join(out,'snippets'),extname:'.liquid',strictFilters:false});
const translations=JSON.parse(fs.readFileSync('theme/locales/en.default.json'));
engine.registerFilter('t',s=>s.split('.').reduce((o,k)=>o?.[k],translations)||s);
engine.registerFilter('money',n=>n == null ? '' : '$'+(n/100).toFixed(2));engine.registerFilter('structured_data',()=>'{"@context":"https://schema.org"}');
engine.registerFilter('default_pagination',()=> '');
engine.registerFilter('asset_url',name=>name);
for(const f of fs.readdirSync('theme/assets'))fs.copyFileSync(path.join('theme/assets',f),path.join(out,f));
const variants=[{id:'11',title:'Single Kneora Massager',price:null,available:true},{id:'12',title:'Kneora Knee Massager + After Care Healing Gel',price:null,available:true}];
const product={id:1,title:'',url:'product.html',variants,selected_or_first_available_variant:variants[0],media:[],has_only_default_variant:false,available:true,price:null,description:''};
const settings={brand:'Kneora',main_product:product,main_menu:{links:[{title:'Shop',url:'product.html'},{title:'How it works',url:'guide.html'},{title:'Our story',url:'about.html'},{title:'Support',url:'contact.html'}]},footer_menu:{links:[{title:'Shop',url:'product.html'},{title:'Support',url:'contact.html'}]}};
const context={settings,request:{design_mode:true},shop:{name:'Kneora',policies:[],enabled_payment_types:[],shipping_policy:{body:''},refund_policy:{body:''}},routes:{root_url:'/',all_products_collection_url:'product.html',cart_url:'cart.html',search_url:'search.html'},cart:{item_count:0,'empty?':true},product};
async function section(type,config={},id=type){let raw=fs.readFileSync('theme/sections/'+type+'.liquid','utf8');const schema=JSON.parse(raw.match(/{% schema %}([\s\S]*?){% endschema %}/)[1]);let defaults={};for(const s of schema.settings||[])if('default'in s)defaults[s.id]=s.default;const blocks=(config.block_order||[]).map(k=>({id:k,...config.blocks[k],shopify_attributes:''}));return engine.parseAndRender(clean(raw),{...context,section:{id,settings:{...defaults,...config.settings},blocks}})}
(async()=>{for(const [file,template] of [['index','index'],['product','product'],['about','page.about'],['guide','page.guide'],['contact','page.contact'],['search','search'],['cart','cart']]){context.template={name:template.split('.')[0]};const config=JSON.parse(fs.readFileSync('theme/templates/'+template+'.json'));let html=await section('header');for(const id of config.order){const s=config.sections[id];html+=await section(s.type,s,id)}html+=await section('footer');fs.writeFileSync(path.join(out,file+'.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kneora design preview</title><link rel="stylesheet" href="kneora.css"><style>:root{--navy:#20364B;--paper:#FAFCFD;--amber:#D5A442;--heading:'Arial Narrow',Arial;--body:Arial}.preview-notice{background:#fff1c8;padding:8px 18px;text-align:center;font:13px Arial}.gallery .editor-placeholder{aspect-ratio:1;display:grid;place-content:center;text-align:center;font-size:19px;padding:60px}</style></head><body data-root="/" data-cart-url="cart.html"><div class="preview-notice">Design preview · Product name, images and prices intentionally blank · Photography and store setup pending</div><main>${html}</main><script src="kneora.js"></script></body></html>`)}for(const f of ['kneora.css','kneora.js'])fs.copyFileSync('theme/assets/'+f,path.join(out,f));console.log('Rendered 7 theme-derived fixture previews.');})();
